name: M3U Listesini Güncelle

on:
  schedule:
    - cron: '0 */12 * * *'  # Her 12 saatte bir çalışır
  workflow_dispatch:         # Manuel tetikleme

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    
    steps:
    - name: Depoyu Kontrol Et
      uses: actions/checkout@v3
      
    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Gerekli Paketleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: M3U Güncelleyiciyi Çalıştır
      run: python umit_m3u_updater.py
      
    - name: Değişiklikleri Kaydet ve Gönder
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Otomatik M3U güncellemesi [$(date +'%d.%m.%Y %H:%M')]" || echo "Değişiklik yok"
        git push
